apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      nodeName_pod1=$(kubectl get pod pod1 -o jsonpath={.spec.nodeName})
      while true; do
                IP2=$(kubectl get pod pod2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod pod2 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod1\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod pod3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod pod3 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod1\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 5;
      done
  nodeSelector:
    pod-assign: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      nodeName_pod2=$(kubectl get pod pod2 -o jsonpath={.spec.nodeName})
      while true; do
                IP1=$(kubectl get pod pod1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod pod1 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod2\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod pod3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod pod3 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod2\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 5;
      done
  nodeSelector:
    pod-assign: node2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      nodeName_pod3=$(kubectl get pod pod3 -o jsonpath={.spec.nodeName})
      while true; do
                IP1=$(kubectl get pod pod1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod pod1 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod3\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP2=$(kubectl get pod pod2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod pod2 -o jsonpath={.spec.nodeName}) && echo "delay{from=\"$nodeName_pod3\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 5;
      done
  nodeSelector:
    pod-assign: node3
---
