apiVersion: v1
kind: Pod
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  containers:
  - image: chung123abc/metrics-server:v2.0
    name: metrics-server
    ports:
    - name: metrics-port
      containerPort: 1323


---

apiVersion: v1
kind: Service
metadata:
  name: metrics-server-service
spec:
  type: NodePort
  selector:
    app: metrics-server
  ports:
    - port: 1323
      targetPort: 1323
      nodePort: 30007