apiVersion: v1
kind: Pod
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  nodeSelector:
    pod-assign: node1
  containers:
  - image: chung123abc/metrics-server:v2.0
    name: metrics-server
    ports:
    - name: metrics-port
      containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server-service
  labels:
    app: metrics-app
spec:
  type: NodePort
  selector:
    app: metrics-server
  ports:
    - name: http-metrics
      port: 9090
      targetPort: 9090